#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Load nvm if available
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Use the version from .nvmrc if it exists
[ -f .nvmrc ] && nvm use

npx lint-staged
